#!/usr/bin/env python3
"""Build a fabricated ~/.claude for screenshots.

The images in the README must not show anyone's real sessions — titles,
prompts, folder names and conversation text are all private. This writes a
plausible but entirely invented corpus into a throwaway HOME, so the
screenshots can be regenerated by anyone without exposing their own history.

    python3 tools/demo-corpus.py /tmp/demo-home
    HOME=/tmp/demo-home python3 tools/screenshot.py docs/list.png 150 24

Pass --reopen-offer to also record a set of sessions as open under an earlier
boot, which is what makes the post-reboot offer appear.
"""
import json, os, pathlib, random, sys, time, uuid

NOW = int(time.time())

# (folder, title, last prompt, age in hours, turns, subagents)
SESSIONS = [
    ("~/api-gateway", "Rate limiting for the public endpoints",
     "ship it once the tests go green", 0.1, 60, 0),
    ("~/api-gateway", "Trace why /v2/search times out under load",
     "try it with the connection pool doubled", 0.4, 120, 7),
    ("~/dotfiles", "Move the prompt into its own function",
     "yes, and keep the git bit lazy", 2, 24, 0),
    ("~/notes", "Tidy the meeting notes template", "merge the two dailies", 5, 18, 0),
    ("~/api-gateway", "Retry budget for the upstream client",
     "what happens if the budget is exhausted mid-request?", 26, 90, 3),
    ("~/parser", "Replace the hand-rolled lexer",
     "keep the error spans, they are the whole point", 30, 210, 12),
    ("~/blog", "Draft the post about static binaries",
     "cut the third section, it repeats the second", 34, 40, 0),
    ("~/parser", "Property tests for the pretty printer",
     "generate the inputs rather than listing them", 52, 150, 0),
    ("~/infra", "Terraform drift on the staging bucket",
     "import it rather than recreating", 74, 65, 4),
    ("~/blog", "Fix the RSS dates", "they are off by a timezone", 96, 22, 0),
    ("~/parser", "Benchmark the arena allocator",
     "measure it against the old one on the same input", 140, 300, 0),
    ("~/infra", "Rotate the deploy keys", "do the staging one first", 180, 48, 0),
    ("~/scratch", "Compare two json dumps", "just the keys that differ", 400, 12, 0),
    ("~/api-gateway", "Audit the error responses",
     "every one should have a request id", 720, 88, 0),
    ("~/parser", "First pass at the grammar", "start from the spec, not the old code", 2400, 140, 0),
]

REPLY = [
    "That reproduces it. The pool is handing out a connection that was already "
    "closed by the upstream, so the first write fails and the retry lands on a "
    "fresh one — which is why it only shows up under load.",
    "Done. The span now carries the byte offset as well as the line, so the "
    "caret lands in the right column when a token spans a newline.",
    "Two things fell out of that: the budget is per-attempt rather than "
    "per-request, and exhausting it returns the last upstream error rather "
    "than a synthetic one.",
    "Benchmarked both on the same corpus: the arena is about a third faster on "
    "allocation-heavy input and identical on everything else.",
    "Fixed, and added a case for it. The dates were being formatted in local "
    "time and parsed as UTC.",
]
ASK = [
    "can you look at why this is slow",
    "what happens if that fails halfway through?",
    "rewrite it so the caller decides",
    "add a test that would have caught this",
    "explain the tradeoff before you change anything",
]


HOME = None  # set in main; the demo cwds live under it so they abbreviate to ~


def real(folder):
    return folder.replace("~", str(HOME))


def enc(path):
    return real(path).replace("/", "-")


def line(**kw):
    return json.dumps(kw, separators=(",", ":"))


def turn(role, text, model, ts, usage=False):
    msg = {"role": role, "content": [{"type": "text", "text": text}]}
    if role == "assistant":
        msg["model"] = model
        if usage:
            msg["usage"] = {
                "input_tokens": random.randint(200, 3000),
                "output_tokens": random.randint(100, 2000),
                "cache_read_input_tokens": random.randint(20000, 400000),
                "cache_creation_input_tokens": random.randint(500, 9000),
            }
    return line(parentUuid="p", isSidechain=False, message=msg, cwd="", type=role,
                uuid=str(uuid.uuid4()), timestamp=ts)


def iso(t):
    return time.strftime("%Y-%m-%dT%H:%M:%S.000Z", time.gmtime(t))


def write_session(root, folder, title, last, age_h, turns, subagents, model, perms):
    sid = str(uuid.uuid4())
    d = root / ".claude" / "projects" / enc(folder)
    d.mkdir(parents=True, exist_ok=True)
    start = NOW - int(age_h * 3600) - turns * 30
    out = [
        line(type="mode", mode="normal", sessionId=sid),
        line(type="permission-mode", permissionMode=perms, sessionId=sid),
    ]
    cwd = real(folder)
    for i in range(turns):
        ts = iso(start + i * 30)
        if i % 2 == 0:
            out.append(line(parentUuid="p", isSidechain=False,
                            message={"role": "user",
                                     "content": [{"type": "text",
                                                  "text": random.choice(ASK)}]},
                            cwd=cwd, gitBranch="main", version="2.1.0",
                            type="user", uuid=str(uuid.uuid4()), timestamp=ts))
        else:
            out.append(turn("assistant", random.choice(REPLY), model, ts, usage=True))
    out.append(line(type="ai-title", aiTitle=title, sessionId=sid))
    out.append(line(type="last-prompt", lastPrompt=last, leafUuid="x", sessionId=sid))
    (d / f"{sid}.jsonl").write_text("\n".join(out) + "\n")

    for n in range(subagents):
        sd = d / sid / "subagents"
        sd.mkdir(parents=True, exist_ok=True)
        aid = f"agent-{uuid.uuid4().hex[:17]}"
        rows = [line(parentUuid=None, isSidechain=True, agentId=aid, cwd=cwd,
                     message={"role": "user",
                              "content": [{"type": "text",
                                           "text": f"Investigate branch {n + 1} and report back."}]},
                     type="user", uuid=str(uuid.uuid4()), timestamp=iso(start + n * 60))]
        rows.append(turn("assistant", random.choice(REPLY), model, iso(start + n * 60 + 30), True))
        (sd / f"{aid}.jsonl").write_text("\n".join(rows) + "\n")
    return sid


def main(dest, reopen_offer=False):
    global HOME
    random.seed(11)
    root = pathlib.Path(dest)
    HOME = root
    if root.exists():
        import shutil
        shutil.rmtree(root)
    root.mkdir(parents=True)

    models = ["claude-opus-5", "claude-opus-5", "claude-sonnet-5", "claude-opus-4-8"]
    ids = []
    for i, (folder, title, last, age, turns, subs) in enumerate(SESSIONS):
        sid = write_session(root, folder, title, last, age, turns, subs,
                            models[i % len(models)],
                            "bypassPermissions" if i % 5 else "default")
        ids.append(sid)
        # make the ages real on disk, since the list sorts on mtime
        p = next((root / ".claude" / "projects" / enc(folder)).glob(f"{sid}.jsonl"))
        t = NOW - int(age * 3600)
        os.utime(p, (t, t))

    # the folders have to exist, or every row is marked as a deleted directory
    for folder in {f for f, *_ in SESSIONS}:
        pathlib.Path(real(folder)).mkdir(parents=True, exist_ok=True)

    meta = {"sessions": {
        ids[1]: {"favorite": True, "tags": ["perf"]},
        ids[5]: {"favorite": True},
        ids[8]: {"tags": ["infra"]},
        ids[10]: {"tags": ["perf"]},
    }}
    md = root / ".claude" / "mnemosyne"
    md.mkdir(parents=True, exist_ok=True)
    (md / "meta.json").write_text(json.dumps(meta, indent=2))

    # Optionally, a set of sessions recorded as open under some earlier boot,
    # so the reopen offer has something to offer. The boot id is deliberately
    # one no machine will ever have, which is what makes the offer appear: it
    # can never match the boot a screenshot is taken in. Off by default, so
    # the other images are not all carrying a banner.
    if reopen_offer:
        workspace = {"current": {"boot": "demo-boot-0000", "saved_at": NOW - 7200,
                                 "sessions": [
            {"id": ids[i], "cwd": real(SESSIONS[i][0]), "model": "claude-opus-5",
             "perms": "bypassPermissions", "title": SESSIONS[i][1]}
            for i in (1, 5, 8)]}}
        (md / "workspace.json").write_text(json.dumps(workspace, indent=2))
    print(f"  wrote {len(SESSIONS)} invented sessions to {root}")


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    main(args[0] if args else "/tmp/mnemosyne-demo-home",
         reopen_offer="--reopen-offer" in sys.argv[1:])
